// try catch  throw finally
let exp = "%45+45+09";

try{
    console.log(eval(exp));
}catch(err){
    console.log("err");
}

console.log("Db commiteed");


